// Converts the enclosure STLs (Gehaeuse/stl/*.stl) into docs/viewer/enclosure.js,
// so the 3D viewer shows exactly the parts that get printed.
//
// Usage (from the repo root): node tools/stl2viewer.mjs
// Run it again whenever an STL was re-exported from gehaeuse.scad.
//
// The data is a plain <script> (no fetch), so the viewer also works when
// index.html is opened straight from the disk. Vertices are merged and
// stored as int16 in 1/100 mm, which keeps the file small.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PARTS = ['control_back', 'control_front', 'sensor_back', 'sensor_front', 'sensor_wedge'];
const Q = 100; // 1/100 mm

// returns a flat array of triangle corners [x, y, z, x, y, z, ...]
function readStl(file) {
  const buf = readFileSync(file);
  const count = buf.length >= 84 ? buf.readUInt32LE(80) : 0;
  if (buf.length === 84 + count * 50) {
    const out = [];
    for (let t = 0; t < count; t++) {
      const o = 84 + t * 50 + 12;
      for (let k = 0; k < 9; k++) out.push(buf.readFloatLE(o + k * 4));
    }
    return out;
  }
  const out = [];
  for (const m of buf.toString('latin1').matchAll(/vertex\s+(\S+)\s+(\S+)\s+(\S+)/g)) {
    out.push(+m[1], +m[2], +m[3]);
  }
  return out;
}

function convert(name) {
  const corners = readStl(join(ROOT, 'Gehaeuse', 'stl', name + '.stl'));
  const map = new Map();
  const verts = [];
  const index = [];
  let dropped = 0;
  for (let c = 0; c < corners.length; c += 9) {
    const tri = [];
    for (let k = 0; k < 3; k++) {
      const q = [0, 1, 2].map((a) => Math.round(corners[c + k * 3 + a] * Q));
      if (q.some((v) => v < -32768 || v > 32767)) throw new Error(name + ': part larger than 327 mm');
      const key = q.join(',');
      let id = map.get(key);
      if (id === undefined) {
        id = verts.length / 3;
        map.set(key, id);
        verts.push(...q);
      }
      tri.push(id);
    }
    // rounding can collapse sliver triangles
    if (tri[0] === tri[1] || tri[1] === tri[2] || tri[0] === tri[2]) {
      dropped++;
      continue;
    }
    index.push(...tri);
  }
  const wide = verts.length / 3 > 65535;
  const v = Buffer.from(new Int16Array(verts).buffer);
  const i = Buffer.from((wide ? new Uint32Array(index) : new Uint16Array(index)).buffer);
  console.log(`${name.padEnd(14)} ${index.length / 3} triangles, ${verts.length / 3} vertices` + (dropped ? `, ${dropped} slivers dropped` : ''));
  return { v: v.toString('base64'), i: i.toString('base64'), i32: wide };
}

const data = {};
for (const p of PARTS) data[p] = convert(p);

const js = '// Generated by tools/stl2viewer.mjs from Gehaeuse/stl/*.stl - do not edit by hand.\n' +
  '// Print orientation as in the STL files. v = int16 xyz in 1/100 mm, i = triangle indices.\n' +
  'window.GAS_ENCLOSURE = ' + JSON.stringify(data, null, 1) + ';\n';
const out = join(ROOT, 'docs', 'viewer', 'enclosure.js');
writeFileSync(out, js);
console.log('written: docs/viewer/enclosure.js (' + Math.round(js.length / 1024) + ' KB)');
